# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'joke_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(628, 385)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.container_widget = QtWidgets.QWidget(Form)
        self.container_widget.setObjectName("container_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.container_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.joke_1 = QtWidgets.QLabel(self.container_widget)
        self.joke_1.setObjectName("joke_1")
        self.verticalLayout.addWidget(self.joke_1)
        self.joke_2 = QtWidgets.QLabel(self.container_widget)
        self.joke_2.setObjectName("joke_2")
        self.verticalLayout.addWidget(self.joke_2)
        self.joke_3 = QtWidgets.QLabel(self.container_widget)
        self.joke_3.setObjectName("joke_3")
        self.verticalLayout.addWidget(self.joke_3)
        self.get_jokes_button = QtWidgets.QPushButton(self.container_widget)
        self.get_jokes_button.setObjectName("get_jokes_button")
        self.verticalLayout.addWidget(self.get_jokes_button)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.container_widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.joke_1.setText(_translate("Form", "Joke_one"))
        self.joke_2.setText(_translate("Form", "Joke_two"))
        self.joke_3.setText(_translate("Form", "Joke_three"))
        self.get_jokes_button.setText(_translate("Form", "Give Me Jokes"))
